# Generated by Django 5.0 on 2023-12-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='Nombre',
        ),
    ]
