# Generated by Django 5.0 on 2023-12-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_name_products_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
