# Generated by Django 5.0 on 2023-12-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_name_category_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cod',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='precio',
        ),
    ]
