# Generated by Django 5.0 on 2023-12-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_cod_products_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AlterField(
            model_name='products',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
